### ISSUE TITLE
Github and Video issues for the RegEx course

### ISSUE THREAD

**Issue by dmelgars** [bonnie/udemy-regex-syntax-examples#1]
-----
Course: Regular Expressions For Beginners And Beyond

Issues in the github files and the video.
The video was viewed on manning.com.
-----

https://github.com/bonnie/udemy-REGEX/blob/main/exercises/regex101/python_instructions.md

1. Line 5 contains incorrect syntax:
for example 'r(?m)a+)'

It should be:
for example r'(?m)a+'

2. Line 14 contains a misspelled word:
quanitifers

It should be:
quantifiers

-----

https://github.com/bonnie/udemy-REGEX/blob/main/exercises/python/3_whitespace_and_boundaries/whitespace_and_boundaries.py

The comments for exercise 13 do not indicate what exercise they are for.

This line:
# Match entire strings that are six characters or longer and

Should be:
# Exercise 13: Match entire strings that are six characters or longer and

-----

https://github.com/bonnie/udemy-REGEX/blob/main/exercises/javascript/3_whitespace_and_boundaries/index.js

The comments for exercise 13 do not indicate what exercise they are for.

This line:
// Match entire strings that are six characters or longer and

Should be:
// Exercise 13: Match entire strings that are six characters or longer and

-----

In the chapter "4.2 Specifying Whitespace Characters" video:

1. At 0:30 you say (and indicate in the video) that \f means a line feed. 

That is incorrect. \f is a form feed.

2. At 3:19 you say "followed by a dot and a star, zero or more newline characters".

It should be "followed by a dot and a star, zero or more non-newline characters".

3. At 3:47 you say "and ends with any number of newline characters".

It should be "and ends with any number of non-newline characters".

-----

In the chapter 5.1 "Whitespace Character Classes" video:

1. At 1:27 you say (and indicate in the video) that \f means a line feed.

That is incorrect. \f is a form feed.

-----

In the chapter 5.3 "Word Boundary Characters" video:

1. At 2:58 you say "so I could say operating systems are fascinating. Now we have stem with a word boundary on either side".

The last part of that should be "Now we have a stem with a non-word boundary on either side".

-----

https://github.com/bonnie/udemy-REGEX/blob/main/exercises/javascript/9_substitution/index.js

The exercises are numbered incorrectly in the comments.

"Exercise 40" should be "Exercise 41".
"Exercise 39" should be "Exercise 40".
"Exercise 38" should be "Exercise 39".
"Exercise 37" should be "Exercise 38".
"Exercise 36" should be "Exercise 37".
"Exercise 35" should be "Exercise 36".

-----

https://github.com/bonnie/udemy-REGEX/blob/main/exercises/python/9_substitution/substitution.py

Exercise 35 is numbered incorrectly in the comments.

"Exercise 35" should be "Exercise 36".

-----

**Comment by bonnie** [comment]
Thank you so much for taking the time to write all this out, @dmelgars! I really appreciate this. I have made the GitHub repo corrections in this PR: https://github.com/bonnie/udemy-REGEX/pull/2, and I will take a look at the video corrections later today. 

Thanks again!

**Comment by dmelgars** [comment]
Some more things...

-----

https://github.com/bonnie/udemy-REGEX/blob/main/exercises/regex101/python_instructions.md

Line 5 still contains incorrect syntax:
for example 'r(?m)a+'

The r should be to the left of the first single quote:
for example r'(?m)a+'

-----

In the manning.com version of the course, the last lecture in each section (2 through 9) is a non-video page that provides a link to the exercises for that section, a link to the Regex 101 web site, and links for the JavaScript and Python instructions.

Section 11 does not have a non-video page with a link to the exercises. The final lecture (11.7) in that section is a video titled "Notes on Exercises". There isn't an "11.8 Exercise 10" page.

-----

The last sentence in the "11.7 Notes on Exercises" video is as follows:

"Okay, with that, take a look at the exercises, and then if you're interested, you can move on to the platform-specific sections that are coming up next."

When I heard that sentence it sounded like there was going to be at least one more section in the course (following Exercise 10 in section 11) that was going to talk about platform-specific things. However, the only section that is coming up next is the final "12. Thank you" section.

Should there be another course section, or am I misinterpreting that final sentence in the 11.7 video? Is the sentence just referring to the platform-specific nature of lookarounds in excercise 10?

-----

**Comment by bonnie** [comment]
Thanks again for these comments! I have update the videos and sent the revised versions to Manning. I really appreciate your time and attention to detail. 😊
